### ISSUE TITLE
Exception in the update function of agent named 'OpenSubtitles.org'

### ISSUE THREAD

**Issue by mfeingol** [plexinc-agents/OpenSubtitles.bundle#1]
http://forums.plexapp.com/index.php/topic/28392-automatic-subtitle-fetching-via-opensubtitles-doesnt-work/page__view__findpost__p__211343

This may be a server-side issue, but we should handle it more gracefully on our side - i.e. not failing opaquely with a critical error in the log.

**Comment by maxGreenblatt** [comment]
Agent has since been re-written. Assuming this isn't an issue any more.
