### ISSUE TITLE
Incorrect subtitle name comparison on windows

### ISSUE THREAD

**Issue by israelrios** [plexinc-agents/OpenSubtitles.bundle#18]
Consider replacing the line in __init__.py:

filename = part.file.rsplit('/',1)[-1]
with:
filename = os.path.split(part.file)[1]

so that the subtitle score computation based on the file name works as expected on windows.

Without that change the score never reaches the 0.6 threshold.

Thanks.

**Comment by sander1** [comment]
Thanks! Fixed with 2cbc62a451cb26e904e3fb322ca3e7ed7fe13471
