### ISSUE TITLE
Brazilian Portuguese subtitles shows as unknown

### ISSUE THREAD

**Issue by israelrios** [plexinc-agents/OpenSubtitles.bundle#19]
Brazilian portuguese subtitles downloaded from opensubtitles are displayed as unknown in the subtitle list.

**Comment by maxGreenblatt** [comment]
I assume you are looking for support for the `pob` and `pb` codes to be supported?

This actually needs to be a ticket against a different repo, so I am going to close this ticket and open in the correct repo.
