### ISSUE TITLE
Multiple Duplicate Subtitles showing up in TV Shows

### ISSUE THREAD

**Issue by trumpy81** [plexinc-agents/OpenSubtitles.bundle#21]
User reports that he has multiple duplicate subtitles showing up for TV Show episodes. If he refreshes a single episode the duplicates disappear, but if he refreshes the entire TV Show then the duplicates return.

Any ideas?

**Comment by maxGreenblatt** [comment]
Is this still an issue? Can I get a link to the forum thread?

**Comment by trumpy81** [comment]
Sorry, I think this issue was corrected, at least I have had no further reports relating to this issue. I should have closed this thread I believe.

I don't even remember opening this GHI ... lol

**Comment by maxGreenblatt** [comment]
No worries - closing.
