### ISSUE TITLE
Subtitles that should be downloaded seems to be rejected

### ISSUE THREAD

**Issue by atrus05** [plexinc-agents/OpenSubtitles.bundle#22]
By the looks of it we are not downloading subs when the hash _is_ matched in some circumstances.
Logs and discussion here: https://plex.slack.com/archives/metadata/p1442223695000336

**Comment by atrus05** [comment]
There seems to be a few issues with the agent. This is similar but not exactly the same: https://forums.plex.tv/discussion/comment/1020189#Comment_1020189 The user stevenjarvis in there only has one language set, and he can't download either. Logs in that thread.
By the looks of it he searches for subs for a movie he has ripped himself from a DVD. And he has encoded it. So there is no sub when one checks for the file size hash. But as I have understood it the agent should then search by name, but the log shows that it does not even try.
Not sure if this is something for you @sander1 or if this is for someone else.

**Comment by maxGreenblatt** [comment]
We decided this all appears to be working as expected (somewhat unfortunately...) - though there is an 'improvement' in the works, see #25
