### ISSUE TITLE
User reports format="" on streams created by OpenSubtitles

### ISSUE THREAD

**Issue by mfeingol** [plexinc-agents/OpenSubtitles.bundle#5]
... specifically for sidecar subs, although the issue may be more widespread.

We need the format attribute when transcoding, so this needs to be set to a valid value.  See MediaInspectorMediaInfo::getSubtitleFormat in the PMS code for valid values.

cf http://forums.plexapp.com/index.php/topic/51015-plexsync-and-subtitles/page__view__findpost__p__321854

**Comment by maxGreenblatt** [comment]
This has been fixed. The users in the thread requested more changes that @m.feingol seemed to reject. Closing.
