### ISSUE TITLE
Improve the algortihm to add come context to help fin the best subtitle

### ISSUE THREAD

**Issue by oncleben31** [plexinc-agents/OpenSubtitles.bundle#7]
I've add a post on the Plex forum to suggest an improvement of the algorithm to avoid having the subs of another movie or shows.
You can read more here : https://forums.plex.tv/index.php/topic/99623-please-fix-the-opensubtitle-metadata-agent-while-waiting-for-a-new-subtitle-managment-system/

**Comment by oncleben31** [comment]
@sander1 I see you are working on the agent. Have you plan to change the algorithm of the selection of the best sub ?
My development is in standby and needs some update. The beta testing is very encouraging but I'm not convinced by the viability to maintain a fork. Can we collaborate on this ?

**Comment by maxGreenblatt** [comment]
We now do checks on filename, imdb id, and season/episode number. Closing.
